gcp_project = "roger-chao-gcp"
gcp_region = "us-west2"
gcp_zone = "us-west2-b"
machine_type = "n1-standard-1"
image = "ubuntu-minimal-1810-cosmic-v20181119a"
instance_name = "rogmanster"
instance_count = "1"
